spring:

summary: This is a stub for starting Spring REST services. It includes basic Boot configuration, Docker, and a About
  service that reads this YAML file.
docs: http://localhost:8080/docs


versions:
 - v1
contacts:
  -
    name: Marcelo
    email: mscaldas@gmail.com
    role: Soft. Architect
---
spring:
   profiles: dev

versions:
  - v1
  - v2

---
spring:
  profiles: qa

versions:
  - v1.1