spring:
  application:
    name: About-Rest

server:
  context-path: /serviceContext
  port: 10000
  apiContext: api
  versionContext: v

configuration:
  pageInfo:
    maxPageSize: 100
    defaultPageSize: 20